### ISSUE TITLE
Access tokens use algo 'PS256' which seems not to be supported/implemented by any token verifier ....

### ISSUE THREAD

**Issue by DeepDiver1975** [Kopano-dev/konnect#1]
The token returned by konnectd looks like this:
![screenshot from 2018-10-16 09-27-29](https://user-images.githubusercontent.com/1005065/46999348-bbd39180-d125-11e8-8c26-90f752b6bc7f.png)

I tried to verify the token using various verification libraries and non of them understands PS256.
Is there a config option to change this? 

Error for Okta: The algorithm "PS256" is not supported or does not implement SignatureInterface.

```php
		$jwtVerifier = (new \Okta\JwtVerifier\JwtVerifierBuilder())
			->setDiscovery(new \Okta\JwtVerifier\Discovery\Oidc())
			->setAdaptor(new \Okta\JwtVerifier\Adaptors\SpomkyLabsJose())
//			->setAudience('api://default')
			->setClientId('ownCloud')
			->setIssuer('https://mykonnect.local:8443')
			->build();

		$jwt = $jwtVerifier->verify($bearerToken);
```

THX

**Comment by longsleep** [comment]
Thanks for your feedback!

> I tried to verify the token using various verification libraries and non of them understands PS256.
This is sad for them, since PS256 is pretty much the way to go if you want to avoid potentially insecure RSA PKCS#1 signatures with keys with low exponent (Bleichenbacher).

> Is there a config option to change this?
Yes.

```
      --signing-method string                 JWT signing method (default "PS256")            
```

as command line argument when starting Konnect. It defines what algorithm is used. 

For RSA keys you can switch to any of the PKCS#1 based variants (RS256,RS384,RS512). Konnect also supports ECSA keys with ES256,ES384,ES512).

**Comment by DeepDiver1975** [comment]
THX a lot @longsleep - I'll give that a try ....

**Comment by longsleep** [comment]
> THX a lot @longsleep - I'll give that a try ....

You are welcome. You seem to use okta-jwt-verifier-php which either uses spomky-labs/jose or firebase/php-jwt where firebase/php-jwt does not support RSA-PSS but spomky-labs/jose does (according to their docs at https://packagist.org/packages/spomky-labs/jose). Maybe you can use spomky-labs/jose?

**Comment by DeepDiver1975** [comment]
> You are welcome. You seem to use okta-jwt-verifier-php which either uses spomky-labs/jose or firebase/php-jwt where firebase/php-jwt does not support RSA-PSS but spomky-labs/jose does (according to their docs at https://packagist.org/packages/spomky-labs/jose). Maybe you can use spomky-labs/jose?

No idea why but they seem to only allow RS256 - no idea why.
https://github.com/okta/okta-jwt-verifier-php/blob/1cef6069221c31607806b54b7d36bd610aecaa13/src/Adaptors/SpomkyLabsJose.php#L36

But even if i set this to PS256 it does not verify the token.

**Comment by DeepDiver1975** [comment]
> No idea why but they seem to only allow RS256 - no idea why.
> [](https://github.com/okta/okta-jwt-verifier-php/blob/1cef6069221c31607806b54b7d36bd610aecaa13/src/Adaptors/SpomkyLabsJose.php#L36)

Raised https://github.com/okta/okta-jwt-verifier-php/issues/24

**Comment by longsleep** [comment]
> Switching to RS256 fixes this. THX for now - let's see what needs to be done these days to support PS256.

Its a valid workaround. Konnect will refuse to start with a RSA key with low exponent anyways (see https://github.com/Kopano-dev/konnect/blob/fe1e8ad23e8e75933cb36e96e99eefdfa4d631f1/cmd/konnectd/utils.go#L150-L151) 

I doubt that there are still SSL libraries out there who generate such keys when using their default settings. So should be good enough to use RS256 in production.
