### ISSUE TITLE
`--log-level` not available for `cookie` ?

### ISSUE THREAD

**Issue by spaceone** [Kopano-dev/konnect#17]
In whatever order I try to start konnectd (via docker) it always fails to start with the error message:
`Error: unknown flag: --log-level`.

`kopano/konnectd:0.9.0 --identifier-client-path ./identifier-univention --iss=https://ucs-sso.school.dev --sign-in-uri=https://ucs-sso.school.dev/fbest/ --log-level debug serve cookie 'https://ucs-sso.school.dev/fbest/?load=custom'`

`kopano/konnectd:0.9.0 --identifier-client-path ./identifier-univention --iss=https://ucs-sso.school.dev --sign-in-uri=https://ucs-sso.school.dev/fbest/ serve --log-level debug cookie 'https://ucs-sso.school.dev/fbest/?load=custom'`

`kopano/konnectd:0.9.0 --identifier-client-path ./identifier-univention --iss=https://ucs-sso.school.dev --sign-in-uri=https://ucs-sso.school.dev/fbest/ serve cookie --log-level debug 'https://ucs-sso.school.dev/fbest/?load=custom'`

`kopano/konnectd:0.9.0 --identifier-client-path ./identifier-univention --iss=https://ucs-sso.school.dev --sign-in-uri=https://ucs-sso.school.dev/fbest/ serve cookie 'https://ucs-sso.school.dev/fbest/?load=custom' --log-level debug`

Is `--log-level` not available when using the cookie backend?

When starting the docker container regulary with `ldap` plugin it seems to be working:
```
/var/lib/konnectd-docker # ps aufx
PID   USER     TIME  COMMAND
    1 nobody    0:01 konnectd serve --identifier-registration-conf /etc/kopano/identifier-registration.yaml --identifier-client-path ./identifier-univention --log-level debug ldap --iss=https://ucs-sso.school.dev
```

**Comment by spaceone** [comment]
Urgs, very old version was used.

**Comment by longsleep** [comment]
Just for completeness sake, the `log-level` flag was added in 0.10.0 and is independent of the used backend argument since it is a flag of the `serve` sub command.
