### ISSUE TITLE
Embedding Konnectd as dependency?

### ISSUE THREAD

**Issue by IljaN** [Kopano-dev/konnect#18]
We are currently working on [wrapping konnectd](https://github.com/owncloud/ocis-konnectd) within a [go-micro](https://github.com/micro/go-micro) service. The idea is to add konnect as a dependency then initialize the [server](https://github.com/Kopano-dev/konnect/blob/cc1d1561d479fb305f636c88dc2c656ca290299a/server/server.go#L46) from go-micro. 

Problem is that there is a fairly large amount of private [bootstrap code](https://github.com/Kopano-dev/konnect/tree/master/cmd/konnectd). To my understanding, the parsing of cli-flags and configs is tightly coupled to the initialization of konnectd.

To solve this a large config struct with all config-parameters could be created to decouple the config from the cli-library and environment. The bootstrap code should receive this struct and validate and parse it to create managers, and construct other required parts of the server.

This is just an idea. Happy to discuss and provide a PR :)

**Comment by longsleep** [comment]
Sounds like a good idea - i would not oppose a PR which would create like a `bootstrap` sub modules which holds the logic currently found in the cmd itself (minus the commandline parsing).

Since lot of things need to happen to startup the services provided by `konnectd` it is not particularly trivial to collect it all and it seems bad if embedding could would need to replicate it all.

**Comment by IljaN** [comment]
As #19 is nearing completion we would like to propose some follow up changes to further improve embedding. 

### Configuration files
Instead of storing the [path](https://github.com/Kopano-dev/konnect/blob/1af826eab2aa7e8b8a7ca83ca1c6b22abf95063c/bootstrap/bootstrap.go#L114) to the file the bootstrap should contain the unmarshaled [config struct](https://github.com/Kopano-dev/konnect/blob/cc1d1561d479fb305f636c88dc2c656ca290299a/identity/clients/models.go#L43). With this change the consumer can decide how the load/un-marshall the config during the boot-process (etcd, hard-coded, different format). This would also decouple the business-logic from any io which should also improve test-ability.

This will require some concept on how to add extension-points to the bootstrap. (Extend interface introduced in #19 ?)

### Assets (index.html)
Similar as above but here the path to index.html would be replaced by an io.reader of  to allow loading assets from an vfs or do some other processing. Identifier-webapp should be optional as it might be hosted on another server.

**Comment by longsleep** [comment]
> As #19 is nearing completion we would like to propose some follow up changes to further improve embedding.

Would you please make a ticket for this - so it can be properly discussed there instead of here. Thanks!

**Comment by longsleep** [comment]
This was implemented, since #19 was merged.
