### ISSUE TITLE
Is there any way to map the user information user info as returned via the userinfo_endpoint to a user in ldap? 

### ISSUE THREAD

**Issue by DeepDiver1975** [Kopano-dev/konnect#2]
## Scenario
0. konnectd is connected to an ldap server
1. Clients use OpenID Connect Protocol and authorize with konnectd
2. Clients send access_token to the relaying party (our server)
3. relaying party wants to query additional information from the ldap server
4. :boom: 

![screenshot from 2018-10-16 14-19-25](https://user-images.githubusercontent.com/1005065/47016703-c48d8d00-d150-11e8-8ce4-033a851d9231.png)
![screenshot from 2018-10-16 14-17-25](https://user-images.githubusercontent.com/1005065/47016704-c5262380-d150-11e8-84ac-790270f6c110.png)

Any hint? THX

**Comment by fbartels** [comment]
Hi @DeepDiver1975 ,

in the decoded access token you will also find the ldap dn:

```
{
  "aud": "playground.js",
  "exp": 1539697763,
  "iat": 1539697163,
  "iss": "https://ucs-3212.kopano.intranet",
  "sub": "hwcFhOeeOqiRmHjY_t3zOsHs9Jsl0THED7rYIzbwkNbL8wyXYLBwaULF93m4Iok87B5ezcqZu7BX_ncyRAWIvA@konnect",
  "kc.isAccessToken": true,
  "kc.authorizedScopes": [
    "openid",
    "profile",
    "email"
  ],
  "kc.identity": {
    "kc.i.dn": "Administrator",
    "kc.i.id": "uid=Administrator,cn=users,dc=kopano,dc=intranet",
    "kc.i.un": "Administrator"
  }
}
```

**Comment by DeepDiver1975** [comment]
Thanks a lot - this way I can save one roundtrip to konnectd. THX

**Comment by fbartels** [comment]
To have it said kc.i.id will look different though, if you are using the Kopano backend and not the ldap one. I personally like the "you can link an openid account yo your ldap account" approach that https://github.com/zorn-v/nextcloud-social-login offers.

**Comment by DeepDiver1975** [comment]
THX @fbartels
