### ISSUE TITLE
SAML Allow for issuer != MetadataEndpoint

### ISSUE THREAD

**Issue by cbxnet-ali** [Kopano-dev/konnect#30]
If used with keycloak as authority, keycloak uses an issuer URI that is different from it's metadata URI. It would be preferable to use a config field in the registration.yaml to account for that.

**Comment by longsleep** [comment]
Thanks for the feedback. Konnect loads the metadata from the configured URI. So all information from there could be used.

Seems like an easy change at  https://github.com/Kopano-dev/konnect/blob/master/identity/authorities/saml2.go#L124-L126 assuming the issuer URI is found in the meta data (for example by using EntityID).

For example

```diff
diff --git a/identity/authorities/saml2.go b/identity/authorities/saml2.go
index 632f003..79fbf2e 100644
--- a/identity/authorities/saml2.go
+++ b/identity/authorities/saml2.go
@@ -122,7 +122,7 @@ func (ar *saml2AuthorityRegistration) Authority() *Details {
 }

 func (ar *saml2AuthorityRegistration) Issuer() string {
-       return ar.metadataEndpoint.String()
+       return ar.serviceProvider.IDPMetadata.EntityID
 }

 func (ar *saml2AuthorityRegistration) Validate() error {
(END)
```

I am looking at https://github.com/keycloak/keycloak/blob/master/services/src/main/resources/idp-metadata-template.xml - can you please check where to find the Issuer URI if its not the metadata URI and report back? 

We could add a configuration field for this if not possible to retrieve the issuer URI from anywhere.

**Comment by cbxnet-ali** [comment]
I just confirmed with my test-setup. Looks like keycloak is using it's entity-id so your fix would be sufficient.

If needed, I could test the fix next monday.

**Comment by longsleep** [comment]
Thanks for confirming - the above path will be included in the next release.
