### ISSUE TITLE
redirect_uri's require trailing slash on logout?

### ISSUE THREAD

**Issue by IljaN** [Kopano-dev/konnect#31]
With the following redirect_uri ```https://localhost:9200``` in identifier-registrataion.yml the login works as expected but the logout does not.

```ERR IdentifierIdentityManager: id_token_hint does not match request error="invalid redirect_uri: https://localhost:9200/" service=konnectd```

Adding a trailing slash fixes it: 
https://github.com/owncloud/ocis-konnectd/commit/222c8e345d2acf5d324822bd726d21abfb26cf76#diff-d11c6bdbb7ee2592e3791942926b64a4R12

@longsleep Is this expected behavior?

**Comment by longsleep** [comment]
@IljaN well, Konnect needs the URL exactly as it is called. In technical sense `https://localhost:9200` is not an URL (it is missing a path). The client adds the path (/) implicitly, so such an URL can never be called. I guess it makes sense to use `/` as path when registering redirect URIs without a path in Konnect.

**Comment by IljaN** [comment]
Thanks :)
