### ISSUE TITLE
Commit f8c1f4a (current top) does not build

### ISSUE THREAD

**Issue by irreleph4nt** [Kopano-dev/konnect#4]
I have just tested my build script on Arch Linux again for konnect, which pulls master from here.
The current top commit f8c1f4a fails with the following error during make:

```
cmd/konnectd/bootstrap_ldap.go:65:20: undefined: "stash.kopano.io/kc/konnect/vendor/stash.kopano.io/kc/konnect/identifier/backends/ldap".AttributeNumericUID
cmd/konnectd/bootstrap_ldap.go:73:81: too many arguments in call to backends.NewLDAPIdentifierBackend
        have (*config.Config, *tls.Config, string, string, string, string, string, string, []string, map[string]string)
        want (*config.Config, *tls.Config, string, string, string, string, string, string, map[string]string)
make: *** [Makefile:41: cmd/konnectd] Fehler 2
==> ERROR: An Error happened in build().
    aborting...
```

With no changes to my build script, the last working commit I tested with is d974b04 which was before the LDAP related changes referenced in issue #3 in this repo.
Let me know if you need any more details, please.

**Comment by longsleep** [comment]
Mhm seems to build fine for me - not sure what is going on for you but you - probably something is wrong with your local go environment / path / setup as you seem to have another konnect vendored in `stash.kopano.io/kc/konnect/vendor/stash.kopano.io/kc/konnect/identifier/backends/ldap`.

**Comment by irreleph4nt** [comment]
I'll try to build this vanilla, following the readme on here to the t. What puzzles me however is that previous commits as pointed out work just fine with my build script unchanged.
Also, did you notice the part about 

```
too many arguments in call to backends.NewLDAPIdentifierBackend
```
That make is exiting with? Looks to me like a call to a function with insufficient parameters. I am not a go developer though.

**Comment by longsleep** [comment]
> That make is exiting with? Looks to me like a call to a function with insufficient parameters. I am not a go developer though.

Yes indeed. This is because you have one Konnect (probably the newer) importing stuff from an older (the one in vendor). No idea how this happens at the moment.

**Comment by longsleep** [comment]
> No idea how this happens at the moment.

Tried it on a fresh machine, no cache what so ever and it works just fine. You have a konnect as a vendor dependency (stash.kopano.io/kc/konnect/vendor/stash.kopano.io/kc/konnect/) which is wrong. Unclear where it came from. Maybe remove the vendor folder and try again.

**Comment by irreleph4nt** [comment]
Thank you for looking into this. 
I myself have also tried building this in a clean chroot as per the Arch Wiki. I am running into the same error every time, though. I have not yet tried building this outside my Distro's recommendation, meaning with pure go. I am not changing anything about your code by the way, so I am not downloading anything inside or outside the script that explains the additional konnect folder in vendor. I'll report back in a few hours.

**Comment by longsleep** [comment]
What Go and Go dep are you using? This is what i tested with
```
root@cosmic1:~/go/src/stash.kopano.io/kc/konnect# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.12"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build564596915=/tmp/go-build -gno-record-gcc-switches"
```
```
root@cosmic1:~/go/src/stash.kopano.io/kc/konnect# dep version
dep:
 version     : v0.5.1
 build date  : 2019-03-11
 git hash    : faa6189
 go version  : go1.12
 go compiler : gc
 platform    : linux/amd64
 features    : ImportDuringSolve=false
```

**Comment by fbartels** [comment]
> the script

did not use Arch in quite a while, but maybe share your script seeing the steps you take before you run into this issue could be helpful.

**Comment by irreleph4nt** [comment]
@fbartels 
The script can be found [here](https://bpaste.net/raw/86093e6fc467) (link expires 2019-03-21 21:24:02).
It's a fairly simple PKGBUILD. All I am doing is replacing some paths to fit Arch's file hierarchy. The build part is fairly close to what you have in the readme here with some tweaks for packaging on Arch as per the [Arch Wiki Guidelines](https://wiki.archlinux.org/index.php/Go_package_guidelines)

@longsleep 
`[user@asrv ~]$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build229974251=/tmp/go-build -gno-record-gcc-switches"`

`[user@asrv ~]$ dep version
dep:
 version     : devel
 build date  : 
 git hash    : 
 go version  : go1.11.5
 go compiler : gc
 platform    : linux/amd64
 features    : ImportDuringSolve=false`

**Comment by irreleph4nt** [comment]
Found the issue, was a PICNIC - I am sorry for bothering you with this. The problem is an additional `dep ensure` that sneaked into my build script.

**Comment by longsleep** [comment]
Thanks for trying Konnect :)
