### ISSUE TITLE
Get memberOf LDAP property as Claim attribute of JWT token.

### ISSUE THREAD

**Issue by adjiandov** [Kopano-dev/konnect#56]
Hello,
We are using UCS with Kopano konnect as OIDC provider and we are having issues getting the memberOf LDAP property.

Is there anyway that this can be configured to be retrieved on the UserInfo api?

Thank you

**Comment by longsleep** [comment]
None of the standard claims defined in OpenID Connect (https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) qualify for any group related information. This information is out of scope for an OpenID Connect provider. To get group information another service is needed (which could use the information in the Konnect access token to find the correct entry in LDAP).
